# Generated by Django 5.1.1 on 2024-10-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.CharField(blank=True, max_length=80, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.carddetails'),
        ),
    ]
