# Generated by Django 5.1.1 on 2024-10-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_carddetails_remove_userprofile_bank_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetails',
            old_name='bank_number',
            new_name='card_number',
        ),
    ]
