# Generated by Django 5.1.1 on 2024-11-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Parking Manager')], default=1),
        ),
    ]
