# Generated by Django 5.1.1 on 2024-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='is_enter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
    ]
