# Generated by Django 5.1.1 on 2024-09-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0003_stay_is_enter_stay_is_leave'),
        ('parking_management', '0002_remove_parking_car_registration'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='is_enter',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='is_leave',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='timestamp_enter',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='timestamp_leave',
        ),
        migrations.CreateModel(
            name='EnterParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_enter', models.DateTimeField(auto_now_add=True, null=True)),
                ('parking_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_management.parking')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_activity.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_leave', models.DateTimeField(auto_now_add=True, null=True)),
                ('parking_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_management.parking')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_activity.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
    ]
