# Generated by Django 5.1.1 on 2024-09-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0004_remove_stay_is_enter_remove_stay_is_leave_and_more'),
        ('parking_management', '0002_remove_parking_car_registration'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterparking',
            name='parking_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.parking'),
        ),
        migrations.AlterField(
            model_name='enterparking',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_activity.stay'),
        ),
        migrations.AlterField(
            model_name='enterparking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.userprofile'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='parking_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.parking'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.userprofile'),
        ),
        migrations.AlterField(
            model_name='leaveparking',
            name='parking_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.parking'),
        ),
        migrations.AlterField(
            model_name='leaveparking',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_activity.stay'),
        ),
        migrations.AlterField(
            model_name='leaveparking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.userprofile'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='parking_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.parking'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.userprofile'),
        ),
    ]
