# Generated by Django 5.1.1 on 2024-10-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0005_alter_enterparking_parking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_activity.stay'),
        ),
    ]
