# Generated by Django 5.1.1 on 2024-10-01 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0006_fee_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='calculated_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
