# Generated by Django 5.1.1 on 2024-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
