# Generated by Django 5.1.1 on 2024-11-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0002_parking_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='max_capacity',
            field=models.FloatField(default='50', max_length=80),
        ),
    ]
