# Generated by Django 5.1.1 on 2024-11-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0005_alter_parking_max_capacity_illegalparking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illegalparking',
            old_name='user',
            new_name='inspector',
        ),
    ]
