# Generated by Django 5.1.1 on 2024-12-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0006_rename_user_illegalparking_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='bank_details',
        ),
    ]
