# Generated by Django 5.1.1 on 2024-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0007_remove_parking_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='radius',
            field=models.CharField(blank=True, default='50', max_length=50, null=True, verbose_name='Radius'),
        ),
    ]
