# Generated by Django 5.1.1 on 2024-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0003_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='stripe_checkout_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
