# Generated by Django 5.1.1 on 2024-10-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_activity', '0004_stay_stripe_checkout_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
