# Generated by Django 5.1.1 on 2024-09-30 14:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0003_alter_parking_user'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=80)),
                ('hour_range', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('timestamp_leave', models.DateTimeField(auto_now_add=True, null=True)),
                ('parking_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_management.parking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.userprofile')),
            ],
        ),
    ]
